# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\my_dev\pythonProject\facecap_frontend\tweak_facecap_frontend\ui\sliders.ui'
#
# Created: Thu May 19 22:38:35 2022
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide6 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 294)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.clampMaxLineEdit = QtWidgets.QLineEdit(Form)
        self.clampMaxLineEdit.setObjectName("clampMaxLineEdit")
        self.verticalLayout.addWidget(self.clampMaxLineEdit)
        self.clampMaxSlider = QtWidgets.QSlider(Form)
        self.clampMaxSlider.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.clampMaxSlider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.clampMaxSlider.setAutoFillBackground(False)
        self.clampMaxSlider.setOrientation(QtCore.Qt.Vertical)
        self.clampMaxSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.clampMaxSlider.setObjectName("clampMaxSlider")
        self.verticalLayout.addWidget(self.clampMaxSlider)
        self.clampMaxLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clampMaxLabel.sizePolicy().hasHeightForWidth())
        self.clampMaxLabel.setSizePolicy(sizePolicy)
        self.clampMaxLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.clampMaxLabel.setObjectName("clampMaxLabel")
        self.verticalLayout.addWidget(self.clampMaxLabel)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.clampMinLineEdit = QtWidgets.QLineEdit(Form)
        self.clampMinLineEdit.setObjectName("clampMinLineEdit")
        self.verticalLayout_2.addWidget(self.clampMinLineEdit)
        self.clampMinSlider = QtWidgets.QSlider(Form)
        self.clampMinSlider.setOrientation(QtCore.Qt.Vertical)
        self.clampMinSlider.setObjectName("clampMinSlider")
        self.verticalLayout_2.addWidget(self.clampMinSlider)
        self.clampMinLabel = QtWidgets.QLabel(Form)
        self.clampMinLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.clampMinLabel.setObjectName("clampMinLabel")
        self.verticalLayout_2.addWidget(self.clampMinLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.offsetLineEdit = QtWidgets.QLineEdit(Form)
        self.offsetLineEdit.setObjectName("offsetLineEdit")
        self.verticalLayout_3.addWidget(self.offsetLineEdit)
        self.offsetSlider = QtWidgets.QSlider(Form)
        self.offsetSlider.setOrientation(QtCore.Qt.Vertical)
        self.offsetSlider.setObjectName("offsetSlider")
        self.verticalLayout_3.addWidget(self.offsetSlider)
        self.offsetLabel = QtWidgets.QLabel(Form)
        self.offsetLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.offsetLabel.setObjectName("offsetLabel")
        self.verticalLayout_3.addWidget(self.offsetLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scaleLineEdit = QtWidgets.QLineEdit(Form)
        self.scaleLineEdit.setObjectName("scaleLineEdit")
        self.verticalLayout_4.addWidget(self.scaleLineEdit)
        self.scaleSlider = QtWidgets.QSlider(Form)
        self.scaleSlider.setOrientation(QtCore.Qt.Vertical)
        self.scaleSlider.setObjectName("scaleSlider")
        self.verticalLayout_4.addWidget(self.scaleSlider)
        self.scaleLabel = QtWidgets.QLabel(Form)
        self.scaleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.scaleLabel.setObjectName("scaleLabel")
        self.verticalLayout_4.addWidget(self.scaleLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.clampMaxLabel.setText(QtWidgets.QApplication.translate("Form", "Clamp Max", None, -1))
        self.clampMinLabel.setText(QtWidgets.QApplication.translate("Form", "Clamp Min", None, -1))
        self.offsetLabel.setText(QtWidgets.QApplication.translate("Form", "Offset", None, -1))
        self.scaleLabel.setText(QtWidgets.QApplication.translate("Form", "Scale", None, -1))

