# testing CI/CD


name: CI

on:
 push:
   branches:
     - main


jobs:
  build_py39:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
    
      - name: Setup Python
        uses: actions/setup-python@v4.7.0
        with:
          # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
          python-version: 3.7
          # The target architecture (x86, x64) of the Python or PyPy interpreter.
          architecture: x64
            

      - name: Build .pyc files
        run:
          echo "test"
          #git checkout main

      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

#      - name: Upload artfacts
#        uses: actions/upload-artifact@v2.2.0
#        with:
#          name: myawesomeartifacts
#          path: ./hdr_library_py39.tar.gz
#          if-no-files-found: error
#          retention-days: 90
