# testing CI/CD


name: CI

on:
  push:
    branches:
      - main


jobs:
  build_py37:
    runs-on: ubuntu-latest

    steps:
      - name: Setup enviroment
        run:
          sudo add-apt-repository ppa:deadsnakes/ppa &&
          sudo apt update &&
          sudo apt install python3.9 -y &&
          sudo apt install python3.9-distutils -y &&
          python3.9 -m pip install -r requirements.txt &&
          python3.9 --version

      - name: Compile .pyc files
        run: echo "python3 --version"
        

