# testing CI/CD


name: CI

#on:
#  push:
#    branches:
#      - main

on:
  push:
    tags:
      - '*'


jobs:
  build_py39:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Clone repo
        uses: actions/checkout@v1
    
      - name: Setup enviroment
        run:
          sudo add-apt-repository ppa:deadsnakes/ppa &&
          sudo apt update &&
          sudo apt install python3.9 -y &&
          sudo apt install python3.9-distutils -y &&
          python3.9 -m pip install -r ./requirements.txt &&
          python3.9 --version

      - name: Build .pyc files
        run: tar czf hdr_library_py39.tar.gz ./widgets

      
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./hdr_library_py39.tar.gz
          asset_name: hdr_library_py39.tar.gz
          asset_content_type: application/gzip
        

